import { useEffect, useState } from "react";
import { getUnreadNotificationCount } from "@cvc/api-client";
import { supabase } from "../lib/supabase";
import { useApp } from "../lib/store";

// Polled count for the header bell badge. Refreshes on bump (when something
// in the app changes notification state) and every 60s as a safety net for
// notifications generated by background jobs / webhooks.
const POLL_MS = 60_000;

export function useUnreadNotifications() {
  const [count, setCount] = useState(0);
  const bump = useApp((s) => s.notificationsBump);

  useEffect(() => {
    let cancelled = false;
    async function load() {
      try {
        const n = await getUnreadNotificationCount(supabase);
        if (!cancelled) setCount(n);
      } catch {
        // Silently ignore — bell will retry on next poll/bump.
      }
    }
    load();
    const id = setInterval(load, POLL_MS);
    return () => {
      cancelled = true;
      clearInterval(id);
    };
  }, [bump]);

  return count;
}
